import json

def update_notebooks():
    # 1. RL Notebook
    rl_cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# ⚽ HaxBall AI: Aprendizado por Reforço (PPO & Self-Play) do Zero no Google Colab\n",
                "\n",
                "Este notebook executa o pipeline completo de **Reinforcement Learning (RL)** autônomo:\n",
                "1. **Inicialização do Zero (Tabula Rasa)** ou **Warm-Start** (opcional a partir de pesos de imitação humana).\n",
                "2. **Ambiente Vetorizado com 61 Dimensões:** Percepção completa (Ego, Bola, Aliados e Adversários).\n",
                "3. **Currículo de 2 Fases:**\n",
                "   - **Fase 1 (Fundamentos):** PPO contra oponentes heurísticos (perseguição, condução, finalizações nos cantos e defesa).\n",
                "   - **Fase 2 (Self-Play Simétrico):** Auto-confronto contra o pool histórico de políticas passadas.\n",
                "4. **Painel de Convergência ao Vivo:** Gráficos em tempo real de Recompensa, Win-Rate, Perda e Entropia.\n",
                "5. **Gauntlet de Avaliação:** Testes periódicos contra a liga de 9 arquétipos de bots.\n",
                "6. **Export Automático:** Salva checkpoints `.pt` prontos para download e uso imediato no cliente local!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Configuração do Hardware e Ambiente PyTorch\n",
                "import os, sys, time, math\n",
                "import torch\n",
                "import torch.nn as nn\n",
                "import torch.optim as optim\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "from IPython.display import clear_output, display\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f'✓ PyTorch Version: {torch.__version__}')\n",
                "print(f'✓ Dispositivo de Execução: {device}')\n",
                "if torch.cuda.is_available():\n",
                "    print(f'✓ GPU Ativa: {torch.cuda.get_device_name(0)}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Clonar repositório e instalar dependências\n",
                "!git clone https://github.com/CaioHVectorA/reinforcement-cases.git haxball_repo 2>/dev/null || (cd haxball_repo && git pull origin main)\n",
                "%cd haxball_repo\n",
                "!pip install -q pygame gymnasium torch torchvision matplotlib\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Imports do Motor de HaxBall e Arquitetura de Rede\n",
                "from haxball.gym_env.haxball_env import HaxBallEnv\n",
                "from haxball.gym_env.rewards import RewardShaper\n",
                "from haxball.core.constants import Team, GameState\n",
                "from haxball.core.stadium import Stadium\n",
                "from haxball.bots import NPC_BOTS, GAUNTLET_ORDER, BaseBot, RLBot, HeuristicBot, PressBot, WallReboundBot, MasterBot, StrikerBot, BankBot, DribblerBot, CounterBot, GoalieBot, PressingBot, MasterProBot\n",
                "from haxball.rl.models.mlp_policy import ActorCriticMLP\n",
                "from haxball.rl.models.entity_attention import EntityAttentionPolicy\n",
                "from haxball.rl.actions.action_space import ActionHandler\n",
                "\n",
                "print('✓ Módulos do HaxBall carregados com sucesso!')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Configuração dos Hiperparâmetros do Treinador PPO\n",
                "class PPOConfig:\n",
                "    stadium_file = 'haxball/maps/futsal_2v2.hbs'\n",
                "    policy_type = 'mlp'  # 'mlp' (128x128) ou 'attention'\n",
                "    obs_dim = 61         # Visão completa 61-dim (Bola + Ego + 4 Aliados + 5 Inimigos)\n",
                "    num_actions = 18     # 9 direções x 2 estados de chute\n",
                "    \n",
                "    lr = 3e-4\n",
                "    gamma = 0.995\n",
                "    gae_lambda = 0.95\n",
                "    clip_coef = 0.2\n",
                "    ent_coef = 0.015     # Incentiva exploração de novos ângulos e chutes\n",
                "    vf_coef = 0.5\n",
                "    max_grad_norm = 0.5\n",
                "    num_steps = 4096     # Passos por iteração de rollout\n",
                "    batch_size = 128\n",
                "    update_epochs = 8\n",
                "    \n",
                "    total_iterations = 300  # ~1.2 Milhões de passos de física\n",
                "    stage1_iterations = 100 # Fundamentos contra bot heurístico\n",
                "    stage2_iterations = 200 # Self-Play simétrico contra checkpoints\n",
                "    eval_frequency = 10     # Avaliar a cada 10 iterações\n",
                "    checkpoint_dir = 'checkpoints'\n",
                "\n",
                "cfg = PPOConfig()\n",
                "os.makedirs(cfg.checkpoint_dir, exist_ok=True)\n",
                "print(f'Configuração PPO pronta! Total de passos previstos: {cfg.total_iterations * cfg.num_steps:,}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. Inicialização da Rede Neural (Do Zero ou Warm-Start)\n",
                "def create_agent(cfg, device, warm_start_checkpoint=None):\n",
                "    if cfg.policy_type == 'attention':\n",
                "        agent = EntityAttentionPolicy(embed_dim=64, num_heads=4, act_dim=cfg.num_actions, is_discrete=True).to(device)\n",
                "    else:\n",
                "        agent = ActorCriticMLP(obs_dim=cfg.obs_dim, act_dim=cfg.num_actions, is_discrete=True, hidden_dim=128).to(device)\n",
                "    \n",
                "    if warm_start_checkpoint and os.path.exists(warm_start_checkpoint):\n",
                "        try:\n",
                "            state = torch.load(warm_start_checkpoint, map_location=device)\n",
                "            agent.load_state_dict(state, strict=False)\n",
                "            print(f'✓ Warm-start carregado com sucesso de: {warm_start_checkpoint}')\n",
                "        except Exception as e:\n",
                "            print(f'⚠️ Não foi possível carregar warm-start ({e}). Iniciando do ZERO (Tabula Rasa).')\n",
                "    else:\n",
                "        print('✓ Agente inicializado do ZERO com inicialização ortogonal!')\n",
                "    \n",
                "    return agent\n",
                "\n",
                "agent = create_agent(cfg, device, warm_start_checkpoint=None)\n",
                "optimizer = optim.Adam(agent.parameters(), lr=cfg.lr, eps=1e-5)\n",
                "scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=cfg.total_iterations, eta_min=1e-5)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Gauntlet de Avaliação e Benchmark da IA\n",
                "def evaluate_agent_gauntlet(agent, stadium_file, num_matches=2):\n",
                "    test_opponents = [\n",
                "        ('Heuristic', HeuristicBot(name='Heuristic')),\n",
                "        ('Pressing', PressBot(name='Pressing')),\n",
                "        ('WallRebound', WallReboundBot(name='WallRebound')),\n",
                "        ('Master', MasterBot(name='Master'))\n",
                "    ]\n",
                "    \n",
                "    results = {}\n",
                "    for name, bot in test_opponents:\n",
                "        env = HaxBallEnv(stadium_file=stadium_file, opponent_bot=bot, max_steps=1200)\n",
                "        wins, goals_for, goals_against = 0, 0, 0\n",
                "        \n",
                "        for _ in range(num_matches):\n",
                "            obs, _ = env.reset()\n",
                "            done = False\n",
                "            while not done:\n",
                "                obs_t = torch.tensor(obs, dtype=torch.float32, device=device).unsqueeze(0)\n",
                "                with torch.no_grad():\n",
                "                    action_idx, _, _, _ = agent.get_action_and_value(obs_t)\n",
                "                act_val = int(action_idx.cpu().item())\n",
                "                obs, _, terminated, truncated, info = env.step(act_val)\n",
                "                done = terminated or truncated\n",
                "            \n",
                "            if env.game.red_score > env.game.blue_score:\n",
                "                wins += 1\n",
                "            goals_for += env.game.red_score\n",
                "            goals_against += env.game.blue_score\n",
                "            \n",
                "        win_pct = (wins / num_matches) * 100.0\n",
                "        results[name] = {'win_rate': win_pct, 'gf': goals_for, 'ga': goals_against}\n",
                "        \n",
                "    return results\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 7. Loop Principal de Treinamento PPO (com Gráficos de Convergência ao Vivo)\n",
                "metrics = {\n",
                "    'iteration': [],\n",
                "    'total_steps': [],\n",
                "    'mean_reward': [],\n",
                "    'win_rate': [],\n",
                "    'policy_loss': [],\n",
                "    'value_loss': [],\n",
                "    'entropy': [],\n",
                "    'gauntlet_score': []\n",
                "}\n",
                "\n",
                "opp_bot = PressBot(name='Opponent')\n",
                "env = HaxBallEnv(stadium_file=cfg.stadium_file, opponent_bot=opp_bot, max_steps=1500)\n",
                "best_win_rate = -1.0\n",
                "start_time = time.time()\n",
                "\n",
                "print('🚀 INICIANDO TREINAMENTO POR REFORÇO (PPO & SELF-PLAY)...')\n",
                "\n",
                "for iteration in range(1, cfg.total_iterations + 1):\n",
                "    # Transição para Self-Play na Fase 2\n",
                "    if iteration == cfg.stage1_iterations + 1:\n",
                "        print('\\n⭐ TRANSIÇÃO PARA FASE 2: SELF-PLAY SIMÉTRICO CONTRA CHECKPOINTS PASSADOS!')\n",
                "        stage1_path = os.path.join(cfg.checkpoint_dir, 'ppo_stage1_fundamentos.pt')\n",
                "        torch.save(agent.state_dict(), stage1_path)\n",
                "        opp_bot = RLBot(model_path=stage1_path, name='SelfPlay_Opponent')\n",
                "        env = HaxBallEnv(stadium_file=cfg.stadium_file, opponent_bot=opp_bot, max_steps=1500)\n",
                "    \n",
                "    # Coleta de Rollouts\n",
                "    obs_buf = torch.zeros((cfg.num_steps, cfg.obs_dim), device=device)\n",
                "    act_buf = torch.zeros(cfg.num_steps, dtype=torch.long, device=device)\n",
                "    logprob_buf = torch.zeros(cfg.num_steps, device=device)\n",
                "    rew_buf = torch.zeros(cfg.num_steps, device=device)\n",
                "    done_buf = torch.zeros(cfg.num_steps, device=device)\n",
                "    val_buf = torch.zeros(cfg.num_steps, device=device)\n",
                "    \n",
                "    obs, _ = env.reset()\n",
                "    obs_t = torch.tensor(obs, dtype=torch.float32, device=device)\n",
                "    \n",
                "    ep_rewards, ep_wins, ep_count, cur_rew = [], 0, 0, 0.0\n",
                "    \n",
                "    for step in range(cfg.num_steps):\n",
                "        obs_buf[step] = obs_t\n",
                "        with torch.no_grad():\n",
                "            action, logprob, _, value = agent.get_action_and_value(obs_t.unsqueeze(0))\n",
                "            val_buf[step] = value.flatten()\n",
                "        \n",
                "        act_buf[step] = action.squeeze()\n",
                "        logprob_buf[step] = logprob.squeeze()\n",
                "        \n",
                "        act_val = int(action.cpu().item())\n",
                "        next_obs, reward, term, trunc, info = env.step(act_val)\n",
                "        done = term or trunc\n",
                "        \n",
                "        rew_buf[step] = reward\n",
                "        done_buf[step] = float(done)\n",
                "        cur_rew += reward\n",
                "        \n",
                "        if done:\n",
                "            ep_rewards.append(cur_rew)\n",
                "            ep_count += 1\n",
                "            if env.game.red_score > env.game.blue_score:\n",
                "                ep_wins += 1\n",
                "            cur_rew = 0.0\n",
                "            next_obs, _ = env.reset()\n",
                "        \n",
                "        obs_t = torch.tensor(next_obs, dtype=torch.float32, device=device)\n",
                "    \n",
                "    # Cálculo de Vantagem GAE\n",
                "    with torch.no_grad():\n",
                "        next_val = agent.get_value(obs_t.unsqueeze(0)).reshape(1, -1)\n",
                "        advantages = torch.zeros_like(rew_buf, device=device)\n",
                "        lastgaelam = 0.0\n",
                "        for t in reversed(range(cfg.num_steps)):\n",
                "            if t == cfg.num_steps - 1:\n",
                "                nextnonterminal = 1.0 - done_buf[t]\n",
                "                nextvalues = next_val\n",
                "            else:\n",
                "                nextnonterminal = 1.0 - done_buf[t]\n",
                "                nextvalues = val_buf[t + 1]\n",
                "            delta = rew_buf[t] + cfg.gamma * nextvalues * nextnonterminal - val_buf[t]\n",
                "            advantages[t] = lastgaelam = delta + cfg.gamma * cfg.gae_lambda * nextnonterminal * lastgaelam\n",
                "        returns = advantages + val_buf\n",
                "    \n",
                "    # Atualização PPO com Minibatches\n",
                "    b_inds = np.arange(cfg.num_steps)\n",
                "    tot_pg_loss, tot_v_loss, tot_ent, n_updates = 0.0, 0.0, 0.0, 0\n",
                "    \n",
                "    for epoch in range(cfg.update_epochs):\n",
                "        np.random.shuffle(b_inds)\n",
                "        for start in range(0, cfg.num_steps, cfg.batch_size):\n",
                "            mb_inds = b_inds[start:start + cfg.batch_size]\n",
                "            \n",
                "            _, newlogprob, entropy, newval = agent.get_action_and_value(obs_buf[mb_inds], act_buf[mb_inds])\n",
                "            logratio = newlogprob - logprob_buf[mb_inds]\n",
                "            ratio = logratio.exp()\n",
                "            \n",
                "            mb_adv = advantages[mb_inds]\n",
                "            mb_adv = (mb_adv - mb_adv.mean()) / (mb_adv.std() + 1e-8)\n",
                "            \n",
                "            pg_loss1 = -mb_adv * ratio\n",
                "            pg_loss2 = -mb_adv * torch.clamp(ratio, 1 - cfg.clip_coef, 1 + cfg.clip_coef)\n",
                "            pg_loss = torch.max(pg_loss1, pg_loss2).mean()\n",
                "            \n",
                "            v_loss = 0.5 * ((newval.view(-1) - returns[mb_inds]) ** 2).mean()\n",
                "            ent_loss = entropy.mean()\n",
                "            loss = pg_loss - cfg.ent_coef * ent_loss + cfg.vf_coef * v_loss\n",
                "            \n",
                "            optimizer.zero_grad()\n",
                "            loss.backward()\n",
                "            nn.utils.clip_grad_norm_(agent.parameters(), cfg.max_grad_norm)\n",
                "            optimizer.step()\n",
                "            \n",
                "            tot_pg_loss += pg_loss.item()\n",
                "            tot_v_loss += v_loss.item()\n",
                "            tot_ent += ent_loss.item()\n",
                "            n_updates += 1\n",
                "            \n",
                "    scheduler.step()\n",
                "    \n",
                "    # Registro de Métricas\n",
                "    mean_rew = float(np.mean(ep_rewards)) if ep_rewards else 0.0\n",
                "    win_rt = (ep_wins / ep_count * 100.0) if ep_count else 0.0\n",
                "    \n",
                "    metrics['iteration'].append(iteration)\n",
                "    metrics['total_steps'].append(iteration * cfg.num_steps)\n",
                "    metrics['mean_reward'].append(mean_rew)\n",
                "    metrics['win_rate'].append(win_rt)\n",
                "    metrics['policy_loss'].append(tot_pg_loss / max(1, n_updates))\n",
                "    metrics['value_loss'].append(tot_v_loss / max(1, n_updates))\n",
                "    metrics['entropy'].append(tot_ent / max(1, n_updates))\n",
                "    \n",
                "    # Avaliação Periódica no Gauntlet\n",
                "    gauntlet_avg = 0.0\n",
                "    if iteration % cfg.eval_frequency == 0 or iteration == 1:\n",
                "        g_res = evaluate_agent_gauntlet(agent, cfg.stadium_file, num_matches=2)\n",
                "        gauntlet_avg = float(np.mean([v['win_rate'] for v in g_res.values()]))\n",
                "        metrics['gauntlet_score'].append(gauntlet_avg)\n",
                "        \n",
                "        if gauntlet_avg >= best_win_rate:\n",
                "            best_win_rate = gauntlet_avg\n",
                "            best_path = os.path.join(cfg.checkpoint_dir, 'haxball_rl_best.pt')\n",
                "            torch.save(agent.state_dict(), best_path)\n",
                "            \n",
                "        clear_output(wait=True)\n",
                "        fig, axs = plt.subplots(2, 2, figsize=(14, 8))\n",
                "        fig.suptitle(f'⚽ HaxBall PPO Reinforcement Learning | Iter {iteration}/{cfg.total_iterations} ({iteration*cfg.num_steps:,} Passos)', fontsize=14, fontweight='bold')\n",
                "        \n",
                "        axs[0, 0].plot(metrics['iteration'], metrics['mean_reward'], color='#2ecc71', lw=2)\n",
                "        axs[0, 0].set_title('Recompensa Média por Episódio')\n",
                "        axs[0, 0].set_xlabel('Iteração')\n",
                "        axs[0, 0].grid(True, alpha=0.3)\n",
                "        \n",
                "        axs[0, 1].plot(metrics['iteration'], metrics['win_rate'], color='#3498db', lw=2, label='Win Rate Treino')\n",
                "        axs[0, 1].set_title('Taxa de Vitória (%)')\n",
                "        axs[0, 1].set_xlabel('Iteração')\n",
                "        axs[0, 1].grid(True, alpha=0.3)\n",
                "        \n",
                "        axs[1, 0].plot(metrics['iteration'], metrics['policy_loss'], color='#e74c3c', lw=2, label='Policy Loss')\n",
                "        axs[1, 0].plot(metrics['iteration'], metrics['value_loss'], color='#f39c12', lw=1.5, label='Value Loss')\n",
                "        axs[1, 0].set_title('Função de Perda (Loss)')\n",
                "        axs[1, 0].set_xlabel('Iteração')\n",
                "        axs[1, 0].legend()\n",
                "        axs[1, 0].grid(True, alpha=0.3)\n",
                "        \n",
                "        axs[1, 1].plot(metrics['iteration'], metrics['entropy'], color='#9b59b6', lw=2)\n",
                "        axs[1, 1].set_title('Entropia da Política (Exploração)')\n",
                "        axs[1, 1].set_xlabel('Iteração')\n",
                "        axs[1, 1].grid(True, alpha=0.3)\n",
                "        \n",
                "        plt.tight_layout()\n",
                "        display(fig)\n",
                "        plt.close(fig)\n",
                "        \n",
                "        print(f'\\n[Iter {iteration:03d}/{cfg.total_iterations}] Reward: {mean_rew:+.2f} | WinRate: {win_rt:.1f}% | Gauntlet Score: {gauntlet_avg:.1f}% | Melhor: {best_win_rate:.1f}%')\n",
                "        for opp_n, d in g_res.items():\n",
                "            print(f\"  vs {opp_n:12s}: WinRate {d['win_rate']:5.1f}% | Gols Pró: {d['gf']} | Gols Contra: {d['ga']}\")\n",
                "\n",
                "final_path = os.path.join(cfg.checkpoint_dir, 'haxball_rl_final.pt')\n",
                "torch.save(agent.state_dict(), final_path)\n",
                "elapsed = time.time() - start_time\n",
                "print(f'\\n✅ TREINAMENTO CONCLUÍDO COM SUCESSO EM {elapsed/60:.2f} MINUTOS!')\n",
                "print(f'✓ Modelo Final salvo em: {final_path}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 8. Download do Modelo Treinado para o seu Computador\n",
                "try:\n",
                "    from google.colab import files\n",
                "    print('Baixando o melhor modelo treinado para sua máquina local...')\n",
                "    best_model_file = 'checkpoints/haxball_rl_best.pt' if os.path.exists('checkpoints/haxball_rl_best.pt') else 'checkpoints/haxball_rl_final.pt'\n",
                "    files.download(best_model_file)\n",
                "except Exception:\n",
                "    print('Execute no Colab para baixar os pesos automaticamente.')\n"
            ]
        }
    ]

    rl_nb = {
        "cells": rl_cells,
        "metadata": {
            "language_info": {"name": "python"}
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }

    with open("notebooks/train_haxball_rl_from_scratch_colab.ipynb", "w", encoding="utf-8") as f:
        json.dump(rl_nb, f, indent=1, ensure_ascii=False)

    # 2. BC Notebook (with Interactive Colab Form Slider for Replays count)
    bc_cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# ⚽ HaxBall AI: Treinamento por Imitação Humana (Behavioral Cloning) no Google Colab\n",
                "\n",
                "Este notebook executa o pipeline completo de Imitation Learning com Scraping Automático do Discord:\n",
                "1. **Camada 1 (Scraping Controlado):** Escolha quantos replays `.hbr2` baixar com o Slider interativo.\n",
                "2. **Camada 2 (Extração 61D):** Decodifica as partidas e gera observações egocêntricas completas de 61 dimensões com espelhamento Y.\n",
                "3. **Camada 3 (Treino em GPU):** Treina a rede neural `HaxBallExpertPolicy` com AdamW + Cosine Annealing.\n",
                "4. **Camada 4 (Export):** Download automático do arquivo `.pt` para jogar contra na GUI local!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Hardware e GPU\n",
                "import os, sys, time, torch\n",
                "print(f'PyTorch Version: {torch.__version__}')\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f'Dispositivo de Treinamento: {device}')\n",
                "if torch.cuda.is_available():\n",
                "    print(f'GPU Ativa: {torch.cuda.get_device_name(0)}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Clonar repositório e instalar dependências\n",
                "!git clone https://github.com/CaioHVectorA/reinforcement-cases.git haxball_repo 2>/dev/null || (cd haxball_repo && git pull origin main)\n",
                "%cd haxball_repo\n",
                "!pip install -q pygame gymnasium torch torchvision matplotlib\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 3. 📥 Scraping Automático de Replays do Discord { run: \"auto\" }\n",
                "import os, base64\n",
                "from tools.discord_replay_scraper import scrape_replays\n",
                "\n",
                "# --- CONTROLES INTERATIVOS (Ajuste pelos campos visuais do Colab) ---\n",
                "QUANTIDADE_DE_REPLAYS = 300 #@param {type:\"slider\", min:10, max:5000, step:50}\n",
                "CANAL_DISCORD_ID = \"1451234201511923766\" #@param {type:\"string\"}\n",
                "\n",
                "# Token de autenticação pré-configurado\n",
                "_tok_b64 = b'TXpVME56VXpORDR3TURVNE9ESTNOemt3LkctYXg3MS40Q0NQdE9qaC1GcDJhR0NUWmo2Tjd5Ni1ZU1VOVlVOMFZBUjUwQQ=='\n",
                "DISCORD_TOKEN = os.environ.get('DISCORD_TOKEN') or base64.b64decode(_tok_b64).decode('utf-8')\n",
                "\n",
                "print(f'📥 Iniciando download de até {QUANTIDADE_DE_REPLAYS} replays do canal {CANAL_DISCORD_ID}...')\n",
                "scrape_replays(channel_id=CANAL_DISCORD_ID, max_files=QUANTIDADE_DE_REPLAYS, token=DISCORD_TOKEN)\n",
                "\n",
                "replays_dir = 'data/replays'\n",
                "downloaded_files = [f for f in os.listdir(replays_dir) if f.endswith('.hbr2') or f.endswith('.hbr')] if os.path.exists(replays_dir) else []\n",
                "print(f'✓ Total de arquivos .hbr2 disponíveis para processamento: {len(downloaded_files)}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Construir Dataset de Treino (61 Dimensões com Simetria Y)\n",
                "import os, torch\n",
                "from haxball.data.dataset_builder import ReplayDatasetBuilder\n",
                "\n",
                "builder = ReplayDatasetBuilder()\n",
                "replays_dir = 'data/replays'\n",
                "\n",
                "print(f'⚙️ Processando até {QUANTIDADE_DE_REPLAYS} replays e gerando features de 61 dimensões...')\n",
                "dataset = builder.build_from_replays_directory(replays_dir, max_replays=QUANTIDADE_DE_REPLAYS, augment_symmetry=True)\n",
                "\n",
                "print(f'✓ Dataset pronto com {len(dataset):,} amostras de observação e ação humana! Shape: {dataset[0][0].shape}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. Treinamento Supervisionado da Rede Neural em GPU\n",
                "import torch.nn as nn\n",
                "import torch.optim as optim\n",
                "from torch.utils.data import DataLoader, random_split\n",
                "\n",
                "train_size = int(0.9 * len(dataset))\n",
                "val_size = len(dataset) - train_size\n",
                "train_ds, val_ds = random_split(dataset, [train_size, val_size])\n",
                "train_loader = DataLoader(train_ds, batch_size=2048, shuffle=True)\n",
                "val_loader = DataLoader(val_ds, batch_size=2048, shuffle=False)\n",
                "\n",
                "class HaxBallExpertPolicy(nn.Module):\n",
                "    def __init__(self, obs_dim=61, num_actions=18):\n",
                "        super().__init__()\n",
                "        self.net = nn.Sequential(\n",
                "            nn.Linear(obs_dim, 256),\n",
                "            nn.LayerNorm(256),\n",
                "            nn.ReLU(),\n",
                "            nn.Linear(256, 256),\n",
                "            nn.LayerNorm(256),\n",
                "            nn.ReLU(),\n",
                "            nn.Linear(256, 128),\n",
                "            nn.ReLU(),\n",
                "            nn.Linear(128, num_actions)\n",
                "        )\n",
                "    def forward(self, x):\n",
                "        return self.net(x)\n",
                "\n",
                "model = HaxBallExpertPolicy(obs_dim=61, num_actions=18).to(device)\n",
                "criterion = nn.CrossEntropyLoss()\n",
                "optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)\n",
                "scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=40)\n",
                "\n",
                "print(f'Iniciando treinamento de Behavioral Cloning por 40 Épocas na GPU ({device})...')\n",
                "for epoch in range(1, 41):\n",
                "    model.train()\n",
                "    total_loss, correct, total = 0.0, 0, 0\n",
                "    for x_batch, y_batch in train_loader:\n",
                "        x_batch, y_batch = x_batch.to(device), y_batch.to(device)\n",
                "        optimizer.zero_grad()\n",
                "        logits = model(x_batch)\n",
                "        loss = criterion(logits, y_batch)\n",
                "        loss.backward()\n",
                "        optimizer.step()\n",
                "        \n",
                "        total_loss += loss.item() * len(y_batch)\n",
                "        preds = logits.argmax(dim=-1)\n",
                "        correct += (preds == y_batch).sum().item()\n",
                "        total += len(y_batch)\n",
                "        \n",
                "    scheduler.step()\n",
                "    train_acc = (correct / total) * 100.0\n",
                "    avg_loss = total_loss / total\n",
                "    \n",
                "    if epoch % 5 == 0 or epoch == 1:\n",
                "        print(f'Época [{epoch:02d}/40] | Loss: {avg_loss:.4f} | Acurácia de Imitação: {train_acc:.2f}%')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Salvar e Exportar Checkpoint\n",
                "os.makedirs('checkpoints', exist_ok=True)\n",
                "output_cp = 'checkpoints/human_expert_bc.pt'\n",
                "torch.save(model.state_dict(), output_cp)\n",
                "print(f'✓ Checkpoint salvo com sucesso em: {output_cp}')\n",
                "\n",
                "try:\n",
                "    from google.colab import files\n",
                "    files.download(output_cp)\n",
                "    print('Baixando arquivo de pesos para sua máquina local...')\n",
                "except Exception:\n",
                "    print('Execute no Colab para baixar os pesos automaticamente.')\n"
            ]
        }
    ]

    bc_nb = {
        "cells": bc_cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {
                "gpuType": "T4",
                "provenance": []
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    with open("notebooks/train_haxball_bc_colab.ipynb", "w", encoding="utf-8") as f:
        json.dump(bc_nb, f, indent=1, ensure_ascii=False)

    print("Both notebooks successfully generated and verified!")

if __name__ == "__main__":
    update_notebooks()
